### ISSUE TITLE
How to use this library

### ISSUE THREAD

**Issue by fangcywangermu** [IslamAAli/ORBSLAM_RTABmap#1]
I am a student, and i am researching intergrating orbslam2 into rtabmap，Oh God I fortunately find your project，could you please tell me how to use your example on my computer, I have installed and run rtabmap on my computer. Thank you very much, respectfully look forward to your reply.

**Comment by IslamAAli** [comment]
Hello, 

Thanks for being interest in our work. It is not a library yet and it was a trial to do an integration of the two algorithms. However the work is still in progress and I don't think that you can benefit from it in its current shape. 

In case we added more into this library i will sure let you know.

Thanks,
